### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by JoeBouchard** [Hack-Weekly/fuchsia-cuttlefish-chat-app#12]
A screen that shows on load up. Maybe an animation? Can be designed with HTML and CSS, SVG voodoo, JavaScript, or even just a gif.

**Comment by thebeatlesphan** [comment]
I've added a splash screen in [merge#26](https://github.com/Hack-Weekly/fuchsia-cuttlefish-chat-app/commit/fb5a99e18a3749f584605a1b965b0b9627f3989f)
