### ISSUE TITLE
need chat room redirect when user not authenticated

### ISSUE THREAD

**Issue by HamzahMansour** [Hack-Weekly/fuchsia-cuttlefish-chat-app#18]
Introduced by https://github.com/Hack-Weekly/fuchsia-cuttlefish-chat-app/pull/14, navigating directly to a chat room (`/r/roomName`) while logged out will result in an error and that isn't handled at all right now -> it should redirect to the main page if user isn't auth'd

for context, this is where routing to specific chat rooms happen:

https://github.com/Hack-Weekly/fuchsia-cuttlefish-chat-app/blob/a63ade9b4e745eef62f91a6aa6a7fc175707f9c7/src/index.js#L12-L15

## possible implementation

add an authstate check and redirect when not authenticated to the ChatBox component, example here

https://github.com/Hack-Weekly/fuchsia-cuttlefish-chat-app/blob/a63ade9b4e745eef62f91a6aa6a7fc175707f9c7/src/components/Profile.js#L7-L9

**Comment by ilmfeemster** [comment]
https://github.com/Hack-Weekly/fuchsia-cuttlefish-chat-app/blob/5acfba5ab0cb5365294ae5f674558a5313b19e58/src/components/ChatBox.js#L20

https://github.com/Hack-Weekly/fuchsia-cuttlefish-chat-app/blob/5acfba5ab0cb5365294ae5f674558a5313b19e58/src/components/ChatBox.js#L44-L62
