### ISSUE TITLE
image upload is messy and sends duplicate images in some cases

### ISSUE THREAD

**Issue by HamzahMansour** [Hack-Weekly/fuchsia-cuttlefish-chat-app#19]
working off of this branch: https://github.com/Hack-Weekly/fuchsia-cuttlefish-chat-app/pull/17, if you upload an image and then send before it's uploaded it'll show an empty message (or with just the caption), until the image is fully uploaded. sending another text-only message while it's being uploaded will send another image message again

## possible implementation

* disable the text input/send button while the last image is being uploaded
* you can check for the progress of the file upload and for any errors that occur similar to what's being done in [this example](https://firebase.google.com/docs/storage/web/upload-files#full_example). So when the upload is state is `running`, we should disable sending more than just the current message with that image attached. And once it's done we clear the `imageURL` state variable properly.

**Comment by thebeatlesphan** [comment]
I want to try to implement this!

**Comment by thebeatlesphan** [comment]
This should be fixed with [merge#35](https://github.com/Hack-Weekly/fuchsia-cuttlefish-chat-app/pull/35)
