### ISSUE TITLE
Splash Screen: can it be made to only load once?

### ISSUE THREAD

**Issue by thebeatlesphan** [Hack-Weekly/fuchsia-cuttlefish-chat-app#29]
The component loads after exiting a chatroom as well.

**Comment by ilmfeemster** [comment]
https://github.com/Hack-Weekly/fuchsia-cuttlefish-chat-app/blob/be833895eeb2e71afba89e43890a46c2c783ce16/src/App.js#L11-L18

https://github.com/Hack-Weekly/fuchsia-cuttlefish-chat-app/blob/be833895eeb2e71afba89e43890a46c2c783ce16/src/App.js#L23
